AllCops:
  Exclude:
    - 'bin/*'
  DisplayCopNames: true
Layout/IndentHeredoc:
  EnforcedStyle: active_support
Style/AndOr:
  AutoCorrect: false
Style/EmptyElse:
  AutoCorrect: false
Style/RaiseArgs:
  AutoCorrect: false
